import localFont from "next/font/local";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Providers from "./Providers";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primaryBlack`}
      >
        <Providers>
          <AntdRegistry> {children} </AntdRegistry>
        </Providers>
      </body>
    </html>
  );
}
